scrape_configs:
  - job_name: Grafana
    scrape_interval: 5s
    static_configs:
      - targets:
        - nodeapp.ditoihkamf.studentdumbways.my.id
        - nodegate.ditoihkamf.studentdumbways.my.id
