- name: update nginx
  hosts: gateway
  tasks:
    - name: ensure nginx is at the latest version
      apt:
        name: nginx
        state: latest
        update_cache: yes
      become: yes

    - name: start nginx
      service:
        name: nginx
        state: started
      become: yes

    - name: copy the nginx config wayshub
      copy:
        src: /home/ditoihkam/1provisioning/ansible/gateway/reverse-proxy-wayshub.conf
        dest: /etc/nginx/sites-enabled/reverse-proxy-wayshub.conf
      become: yes

    - name: restart nginx
      become: yes
      service:
        name: nginx
        state: restarted
