---
- hosts: gateway
  gather_facts: false
  tasks:
    - name: Clone GitHub Repository
      git:
        repo: https://github.com/dumbwaysdev/wayshub-frontend
        dest: /home/ditoihkam/wayshub-frontend
      when: not ansible_check_mode


    - name: Copy Dockerfile fe
      copy:
        src: /home/ditoihkam/ias/Dockerfile
        dest: /home/ditoihkam/wayshub-frontend/Dockerfile
      when: not ansible_check_mode


    - name: Copy Docker-compose.yml
      copy:
        src: /home/ditoihkam/ias/docker-compose.yml
        dest: /home/ditoihkam/docker-compose.yml
      when: not ansible_check_mode


    - name: Run docker-compose
      docker_compose:
        project_src: /home/ditoihkam/
        state: present
