- hosts: all
  become: true
  tasks:
    - name: Create user
      user:
        name: ditoihkamp
        groups: sudo
        state: present
        shell: /bin/bash
        system: no
        createhome: yes
        home: /home/ditoihkamp

    - name: Copy SSH public key to remote host
      authorized_key:
        user: ditoihkamp
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present

    - name: Change PasswordAuthentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify:
        - Restart SSH

  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
