- hosts: monitoring
  become: true
  tasks:
    - name: Stop and remove existing prometheus container
      community.docker.docker_container:
        name: prometheus
        state: absent

    - name: Pull Prometheus Docker image
      community.docker.docker_image:
        name: prom/prometheus
        source: pull

    - name: Create directory for Prometheus config
      file:
        path: /home/ditoihkam/prometheus
        state: directory
        mode: '0755'

    - name: copy prometheus config file
      copy:
        src: 6sprometheus.yml
        dest: /home/ditoihkam/prometheus/6sprometheus.yml

    - name: Run Prometheus on Docker
      community.docker.docker_container:
        name: prometheus
        image: prom/prometheus
        ports:
          - "9091:9090"
        restart_policy: unless-stopped
        volumes:
          - /home/ditoihkam/prometheus/6sprometheus.yml:/etc/prometheus/6sprometheus.yml
        state: started
